services:
  postgres:
    image: postgres:17.3-alpine
    container_name: didomi_challenge_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - didomi_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  rabbitmq:
    image: rabbitmq:4.1-rc-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - didomi_network

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: npm run start:dev users
    env_file:
      - ./apps/users/.env
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app

  consents:
    build:
      context: .
      dockerfile: ./apps/consents/Dockerfile
      target: development
    command: npm run start:dev consents
    env_file:
      - ./apps/consents/.env
    ports:
      - 3002:3002
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data:
    driver: local

networks:
  didomi_network:
    driver: bridge
